server:
  port: 8080
  servlet:
    context-path: /

spring:
    application:
      name: security
    jpa:
      show-sql: true
      generate-ddl: false
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8&serverTimezone=UTC
      username: security
      password: security
    thymeleaf:
      cache: false
      encoding: UTF-8
      prefix: classpath:/templates/
      mode: HTML
      suffix: .html

logging:
  level:
    root: INFO
    com.woojkk.mfa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace